### PR TITLE
Add minimal endorsement

### LINKED ISSUE #3: Create minimal Endorsement.sol

### PR DESCRIPTION
**Pull request by arraysius**
Closes #3

### CODE REVIEW

**Review by Kair0s3 — COMMENTED** [review]
Looks good, just the AddressSet probably need to verify if we can use

**Comment by rizemon** [comment]
Was thinking we could import from online (see below), but turns out `truffle` might not support and perhaps it would be safer to just include a local copy in our repo.

```
import "https://github.com/rob-Hitchens/SetTypes/blob/master/contracts/AddressSet.sol";
```

**Comment by arraysius** [comment]
> Was thinking we could import from online (see below), but turns out `truffle` might not support and perhaps it would be safer to just include a local copy in our repo.
> 
> ```
> import "https://github.com/rob-Hitchens/SetTypes/blob/master/contracts/AddressSet.sol";
> ```

@rizemon 

I had to tweak the library because certain array functions are deprecated in solidity ^0.6.0. And since the default compiler we are using is newer, importing would not work. So remaining on a local copy would be safer.

**Review by kelvneo — APPROVED** [review]
LGTM

**Review by Kair0s3 — APPROVED** [review]
LG!

**Pull request merged**
